/*
 * PanelNuevoEmpleado.java
 *
 * Created on 13/07/2010, 02:16:26 PM
 */

package registrocontrol;

import registrocontrol.clases.Empleado;
import registrocontrol.clases.Historialaboral;
import registrocontrol.clases.Vinculacion;
import java.awt.Component;
import java.awt.Image;
import java.awt.image.RenderedImage;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.util.Calendar;
import java.util.Locale;
import java.util.Enumeration;
import java.util.List;
import javax.imageio.ImageIO;
import javax.persistence.Query;
import javax.swing.AbstractButton;
import javax.swing.DefaultListCellRenderer;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JTextField;
import javax.swing.ListCellRenderer;
import javax.swing.filechooser.FileFilter;
import registrocontrol.lib.Imagen;
import registrocontrol.lib.Mensajes;
import registrocontrol.lib.Valida;

/**
 *
 * @author gurzaf
 */
public class PanelNuevoEmpleado extends javax.swing.JPanel {

    private RegistroControlView registroControlView;
    private Empleado empleado;
    private Historialaboral cargo;
    private Image foto;
    private boolean nuevo;
    
    /** Creates new form PanelNuevoEmpleado */
    public PanelNuevoEmpleado(RegistroControlView registroControlView) {
        nuevo=true;
        this.registroControlView=registroControlView;
        initComponents();
        entityManager.getTransaction().begin();
    }

    public PanelNuevoEmpleado(RegistroControlView registroControlView,long idEmpleado) {
        nuevo=false;
        this.registroControlView=registroControlView;
        initComponents();
        entityManager.getTransaction().begin();
        this.empleado=entityManager.find(Empleado.class, idEmpleado);
        campoId.setText(empleado.getIdEmpleado()+"");
        campoId.setEditable(false);
        botonLimpiar.setEnabled(false);
        campoNombres.setText(empleado.getNombres());
        campoApellido.setText(empleado.getApellidos());
        Calendar cal = Calendar.getInstance();
        cal.setTime(empleado.getFechaNacimiento());
        dateChooserDialog1.setSelectedDate(cal);
        campoFecha.setText(fechaSeleccionada());
        campoDireccion.setText(empleado.getDireccion());
        campoTelefono.setText(empleado.getTelefono()+"");
        campoCorreo.setText(empleado.getEmail());
        for(int i=0;i<campoSangre.getItemCount();i++){
            if(campoSangre.getItemAt(i).toString().equals(empleado.getTipoSangre()))
            {
                campoSangre.setSelectedIndex(i);
                break;
            }
        }
        if(empleado.getRh()==jRadioButton1.getActionCommand().charAt(0))
            jRadioButton1.setSelected(true);
        else jRadioButton2.setSelected(true);
        campoVinculacion.setSelectedItem(empleado.getVinculacion());
        Query q = entityManager.createNamedQuery("Historialaboral.findByIdEmpleado");
           q.setParameter("idEmpleado", empleado.getIdEmpleado());
           List<Historialaboral> listaCargos = q.getResultList();
           for (Historialaboral historialaboral : listaCargos) {

                    if(historialaboral.getFechaSalida()==null){
                        cargo=historialaboral;
                        campoCargo.setText(cargo.getCargo());
                        cal.setTime(cargo.getFechaInicio());
                        campoFechaVincu.setSelectedDate(cal);
                        campoSalario.setText(cargo.getSalarioBase()+"");
                        break;
                    }
           }
        try {
            foto = ImageIO.read(new ByteArrayInputStream(empleado.getFoto()));
        } catch (IOException ex) {
            System.out.println(ex);
        }
        labelFoto.setIcon(new ImageIcon(foto));
        
    }


    private char rhSeleccionado(){
        Enumeration<AbstractButton> botones =  campoRH.getElements();
        while (botones.hasMoreElements()) {
            AbstractButton tmp = botones.nextElement();
            if(tmp.isSelected())
                return tmp.getActionCommand().charAt(0);

        }
        return '+';
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        dateChooserDialog1 = new datechooser.beans.DateChooserDialog();
        campoRH = new javax.swing.ButtonGroup();
        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("RPU").createEntityManager();
        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(registrocontrol.RegistroControlApp.class).getContext().getResourceMap(PanelNuevoEmpleado.class);
        vinculacionQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery(resourceMap.getString("vinculacionQuery.query")); // NOI18N
        vinculacionList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : vinculacionQuery.getResultList();
        escogeImagen = new javax.swing.JFileChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        campoId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        campoNombres = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        campoApellido = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        campoFecha = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        campoDireccion = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        campoTelefono = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        campoCorreo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        campoVinculacion = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        campoCargo = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        campoFoto = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jButton3 = new javax.swing.JButton();
        botonLimpiar = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        campoFechaVincu = new datechooser.beans.DateChooserCombo();
        campoSangre = new javax.swing.JComboBox();
        jButton6 = new javax.swing.JButton();
        labelFoto = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        campoSalario = new javax.swing.JTextField();

        dateChooserDialog1.setNothingAllowed(false);
        dateChooserDialog1.setMaxDate(Calendar.getInstance());
        dateChooserDialog1.addCommitListener(new datechooser.events.CommitListener() {
            public void onCommit(datechooser.events.CommitEvent evt) {
                dateChooserDialog1OnCommit(evt);
            }
        });

        escogeImagen.setApproveButtonText(resourceMap.getString("escogeImagen.approveButtonText")); // NOI18N
        escogeImagen.setApproveButtonToolTipText(resourceMap.getString("escogeImagen.approveButtonToolTipText")); // NOI18N
        escogeImagen.setDialogTitle(resourceMap.getString("escogeImagen.dialogTitle")); // NOI18N
        escogeImagen.setFileFilter(setFileFilter());
        escogeImagen.setFileHidingEnabled(false);
        escogeImagen.setName("escogeImagen"); // NOI18N
        escogeImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                escogeImagenActionPerformed(evt);
            }
        });

        setName("Form"); // NOI18N

        jScrollPane1.setName("jScrollPane1"); // NOI18N
        jScrollPane1.setPreferredSize(new java.awt.Dimension(457, 700));

        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(455, 630));

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jSeparator1.setName("jSeparator1"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        campoId.setText(resourceMap.getString("campoId.text")); // NOI18N
        campoId.setName("campoId"); // NOI18N

        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        campoNombres.setText(resourceMap.getString("campoNombres.text")); // NOI18N
        campoNombres.setName("campoNombres"); // NOI18N

        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        campoApellido.setText(resourceMap.getString("campoApellido.text")); // NOI18N
        campoApellido.setName("campoApellido"); // NOI18N

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        campoFecha.setText(resourceMap.getString("campoFecha.text")); // NOI18N
        campoFecha.setEnabled(false);
        campoFecha.setFocusable(false);
        campoFecha.setName("campoFecha"); // NOI18N

        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        campoDireccion.setText(resourceMap.getString("campoDireccion.text")); // NOI18N
        campoDireccion.setName("campoDireccion"); // NOI18N

        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N

        campoTelefono.setText(resourceMap.getString("campoTelefono.text")); // NOI18N
        campoTelefono.setName("campoTelefono"); // NOI18N

        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N

        campoCorreo.setText(resourceMap.getString("campoCorreo.text")); // NOI18N
        campoCorreo.setName("campoCorreo"); // NOI18N

        jLabel9.setText(resourceMap.getString("jLabel9.text")); // NOI18N
        jLabel9.setName("jLabel9"); // NOI18N

        jLabel10.setText(resourceMap.getString("jLabel10.text")); // NOI18N
        jLabel10.setName("jLabel10"); // NOI18N

        campoRH.add(jRadioButton1);
        jRadioButton1.setSelected(true);
        jRadioButton1.setText(resourceMap.getString("jRadioButton1.text")); // NOI18N
        jRadioButton1.setName("jRadioButton1"); // NOI18N

        campoRH.add(jRadioButton2);
        jRadioButton2.setText(resourceMap.getString("jRadioButton2.text")); // NOI18N
        jRadioButton2.setName("jRadioButton2"); // NOI18N

        jLabel11.setText(resourceMap.getString("jLabel11.text")); // NOI18N
        jLabel11.setName("jLabel11"); // NOI18N

        campoVinculacion.setName("campoVinculacion"); // NOI18N
        if(vinculacionList.isEmpty()){
            Mensajes.Error(this, "No se pueden ingresar empleados si"
                + " no existen tipos de vinculación");
            campoVinculacion.setEnabled(false);
        }
        else{
            campoVinculacion.setRenderer(new VinculacionCellRenderer());

            org.jdesktop.swingbinding.JComboBoxBinding jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, vinculacionList, campoVinculacion);
            bindingGroup.addBinding(jComboBoxBinding);

        }

        jLabel12.setText(resourceMap.getString("jLabel12.text")); // NOI18N
        jLabel12.setName("jLabel12"); // NOI18N

        campoCargo.setText(resourceMap.getString("campoCargo.text")); // NOI18N
        campoCargo.setName("campoCargo"); // NOI18N

        jLabel13.setText(resourceMap.getString("jLabel13.text")); // NOI18N
        jLabel13.setName("jLabel13"); // NOI18N

        campoFoto.setText(resourceMap.getString("campoFoto.text")); // NOI18N
        campoFoto.setEnabled(false);
        campoFoto.setFocusable(false);
        campoFoto.setName("campoFoto"); // NOI18N

        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jSeparator2.setName("jSeparator2"); // NOI18N

        jButton3.setText(resourceMap.getString("jButton3.text")); // NOI18N
        jButton3.setName("jButton3"); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                procesarFormulario(evt);
            }
        });

        botonLimpiar.setText(resourceMap.getString("botonLimpiar.text")); // NOI18N
        botonLimpiar.setName("botonLimpiar"); // NOI18N
        botonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonLimpiarActionPerformed(evt);
            }
        });

        jLabel14.setText(resourceMap.getString("jLabel14.text")); // NOI18N
        jLabel14.setName("jLabel14"); // NOI18N

        campoFechaVincu.setNothingAllowed(false);
        campoFechaVincu.setFormat(1);
        campoFechaVincu.setCurrentNavigateIndex(0);

        campoSangre.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "B", "AB", "O" }));
        campoSangre.setName("campoSangre"); // NOI18N

        jButton6.setText(resourceMap.getString("jButton6.text")); // NOI18N
        jButton6.setName("jButton6"); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        labelFoto.setIcon(new ImageIcon(selecFoto(false)));
        labelFoto.setText(resourceMap.getString("labelFoto.text")); // NOI18N
        labelFoto.setName("labelFoto"); // NOI18N
        labelFoto.setPreferredSize(new java.awt.Dimension(175, 175));

        jLabel15.setText(resourceMap.getString("jLabel15.text")); // NOI18N
        jLabel15.setName("jLabel15"); // NOI18N

        campoSalario.setText(resourceMap.getString("campoSalario.text")); // NOI18N
        campoSalario.setName("campoSalario"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE)
                            .addComponent(jLabel1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelFoto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel15))
                                        .addGap(16, 16, 16)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(campoSalario, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                                            .addComponent(campoFechaVincu, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                                            .addComponent(campoCargo, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(campoSangre, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel10)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jRadioButton2))
                                            .addComponent(campoVinculacion, 0, 286, Short.MAX_VALUE)
                                            .addComponent(campoCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                                            .addComponent(campoTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                                            .addComponent(campoDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addComponent(campoFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(campoNombres, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                                            .addComponent(campoApellido, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                                            .addComponent(campoId, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE))))
                                .addGap(0, 0, 0))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(16, 16, 16)
                                .addComponent(campoFoto, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton6))
                            .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botonLimpiar)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(campoNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(campoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(campoFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(campoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(campoCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(campoSangre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton1)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(campoVinculacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(campoCargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(campoFechaVincu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(campoSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelFoto, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(campoFoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(botonLimpiar))
                .addGap(50, 50, 50))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
        );

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dateChooserDialog1.showDialog(null, true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void dateChooserDialog1OnCommit(datechooser.events.CommitEvent evt) {//GEN-FIRST:event_dateChooserDialog1OnCommit
        campoFecha.setText(fechaSeleccionada());
    }//GEN-LAST:event_dateChooserDialog1OnCommit

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        escogeImagen.showOpenDialog(this);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void escogeImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_escogeImagenActionPerformed
        foto=null;
        campoFoto.setText(escogeImagen.getSelectedFile().getName());
        labelFoto.setIcon(new ImageIcon(selecFoto(true)));
    }//GEN-LAST:event_escogeImagenActionPerformed

    private void procesarFormulario(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_procesarFormulario
         if(!Valida.isId(campoId.getText()))
            error("No se ingreso una identificación válida", campoId);
        else if(!Valida.isPalabra(campoNombres.getText()))
            error("El nombre ingresado no es válido", campoNombres);
        else if(!Valida.isPalabra(campoApellido.getText()))
            error("El apellido indicado no es válido", campoApellido);
        else if(campoFecha.getText().isEmpty())
            error("No se ha seleccionado fecha de nacimiento", jButton1);
        else if(!Valida.isPalabra(campoDireccion.getText()))
            error("No ha indicado una dirección correcta", campoDireccion);
        else if(!Valida.isTelefono(campoTelefono.getText()))
            error("No ha indicado un número de teléfono valido", campoTelefono);
        else if(!Valida.isEmail(campoCorreo.getText()))
            error("Indique una dirección de correo electrónico válida", campoCorreo);
        else if(!campoVinculacion.isEnabled())
            error("Seleccione un tipo de Vinculación", campoVinculacion);
        else if(!Valida.isPalabra(campoCargo.getText()))
            error("Indique el cargo actual del empleado", campoCargo);
         else if(!Valida.isSalario(campoSalario.getText()))
             error("Indique un salario valido",campoSalario);
         else{
            try{
                if(empleado==null)
                empleado = new Empleado(Long.parseLong(campoId.getText()));
                empleado.setNombres(campoNombres.getText());
                empleado.setApellidos(campoApellido.getText());
                empleado.setFechaNacimiento(dateChooserDialog1.getSelectedDate().getTime());
                empleado.setDireccion(campoDireccion.getText());
                empleado.setTelefono(Long.parseLong(campoTelefono.getText()));
                empleado.setEmail(campoCorreo.getText());
                empleado.setTipoSangre(campoSangre.getSelectedItem().toString());
                empleado.setRh(rhSeleccionado());
                empleado.setVinculacion((Vinculacion) campoVinculacion.getSelectedItem());
                if(foto==null){
                if(campoFoto.getText().isEmpty())
                {
                        foto = selecFoto(false);
                }else{
                        foto = selecFoto(true);
                }
                }
                ByteArrayOutputStream bas = new ByteArrayOutputStream();
                ImageIO.write((RenderedImage) foto,"png",bas);
                byte[] fotoByte = bas.toByteArray();
                empleado.setFoto(fotoByte);
                if(cargo==null)
                    cargo = new Historialaboral();
                cargo.setCargo(campoCargo.getText());
                cargo.setFechaInicio(campoFechaVincu.getSelectedDate().getTime());
                cargo.setSalarioBase(Integer.parseInt(campoSalario.getText()));
                cargo.setEmpleado(empleado);
                if(nuevo)
                {
                    entityManager.persist(empleado);
                    entityManager.persist(cargo);
                }
                entityManager.getTransaction().commit();
                Mensajes.Ok(this, "El Empleado se ha guardado correctamente");
                registroControlView.cambiarPanelPrincipal(new PanelListaEmpleados(registroControlView));
            }catch(Exception w){
                Mensajes.Error(this, "Error guardando el nuevo empleado!!");
                System.out.println(w);
                if(!nuevo)
                    registroControlView.cambiarPanelPrincipal(new PanelNuevoEmpleado(registroControlView,empleado.getIdEmpleado()));
            }
            entityManager.getTransaction().begin();
         }
    }//GEN-LAST:event_procesarFormulario

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
            campoFoto.setText("");
            labelFoto.setIcon(new ImageIcon(selecFoto(false)));
            foto=null;
    }//GEN-LAST:event_jButton6ActionPerformed

    private void botonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLimpiarActionPerformed
            registroControlView.cambiarPanelPrincipal(new PanelNuevoEmpleado(registroControlView));
    }//GEN-LAST:event_botonLimpiarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonLimpiar;
    private javax.swing.JTextField campoApellido;
    private javax.swing.JTextField campoCargo;
    private javax.swing.JTextField campoCorreo;
    private javax.swing.JTextField campoDireccion;
    private javax.swing.JTextField campoFecha;
    private datechooser.beans.DateChooserCombo campoFechaVincu;
    private javax.swing.JTextField campoFoto;
    private javax.swing.JTextField campoId;
    private javax.swing.JTextField campoNombres;
    private javax.swing.ButtonGroup campoRH;
    private javax.swing.JTextField campoSalario;
    private javax.swing.JComboBox campoSangre;
    private javax.swing.JTextField campoTelefono;
    private javax.swing.JComboBox campoVinculacion;
    private datechooser.beans.DateChooserDialog dateChooserDialog1;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JFileChooser escogeImagen;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel labelFoto;
    private java.util.List vinculacionList;
    private javax.persistence.Query vinculacionQuery;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    class VinculacionCellRenderer implements ListCellRenderer{
            private DefaultListCellRenderer defaultRenderer = new DefaultListCellRenderer();

        public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
           JLabel renderer = (JLabel) defaultRenderer.getListCellRendererComponent(list, value, index,
        isSelected, cellHasFocus);
            
           Vinculacion vinculacion = (Vinculacion) value;
           renderer.setText(vinculacion.getDescripcion());
            
           return renderer;
        }
    
    }

    private FileFilter setFileFilter()
    {
            FileFilter fileFilter = new FileFilter() {
            @Override
            public boolean accept(File f) {
                return f.getName().toLowerCase().endsWith(".jpeg") || f.getName().toLowerCase().endsWith(".jpg")
                        || f.getName().toLowerCase().endsWith(".gif") || f.getName().toLowerCase().endsWith(".png")
                        || f.isDirectory();
            }

            @Override
            public String getDescription() {
                return "Archivos de Imágen";
            }
            };

            return fileFilter;
    }

    private void error(String mensaje, Component campo){
        Mensajes.Error(this, mensaje);
        campo.requestFocus();
        if(campo instanceof JTextField)
        {
            JTextField jt = (JTextField) campo;
            jt.selectAll();
        }
    }
    
    public Image selecFoto(boolean b){
        try {
            if(b)
                return Imagen.scale(escogeImagen.getSelectedFile(), 175, 175, true, false);
            else{
                return javax.imageio.ImageIO.read(getClass().getResource("/registrocontrol/resources/foto.png").openStream());
            }
        } catch (IOException ex) {
           Mensajes.Error(this, "No se encontro la imágen");
        }
        return null;
    }

    private String fechaSeleccionada(){
        String fechita = dateChooserDialog1.getSelectedDate().get(Calendar.DATE)+" de ";
        fechita+=dateChooserDialog1.getSelectedDate().getDisplayName(Calendar.MONTH, Calendar.LONG, Locale.getDefault());
        fechita+=" de "+dateChooserDialog1.getSelectedDate().get(Calendar.YEAR);
        return fechita;
    }

}
